services:
  category-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: category-ai-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production